// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa7kGicUmPfm3cye1UZSKb9nkf21imSIs',
    appId: '1:899422984435:web:6f28de51fb0bcf5980ff86',
    messagingSenderId: '899422984435',
    projectId: 'flutterauth-fa064',
    authDomain: 'flutterauth-fa064.firebaseapp.com',
    storageBucket: 'flutterauth-fa064.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnMU5dSZ6fMG-rsIo_NkbzTehDs0oTET0',
    appId: '1:899422984435:android:dfefcecc1351eefd80ff86',
    messagingSenderId: '899422984435',
    projectId: 'flutterauth-fa064',
    storageBucket: 'flutterauth-fa064.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEEc_jvwzeJX1qtTCkcviI3RrCF0Suwg0',
    appId: '1:899422984435:ios:6d881a96a2dc812f80ff86',
    messagingSenderId: '899422984435',
    projectId: 'flutterauth-fa064',
    storageBucket: 'flutterauth-fa064.firebasestorage.app',
    iosBundleId: 'com.example.mytravel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEEc_jvwzeJX1qtTCkcviI3RrCF0Suwg0',
    appId: '1:899422984435:ios:6d881a96a2dc812f80ff86',
    messagingSenderId: '899422984435',
    projectId: 'flutterauth-fa064',
    storageBucket: 'flutterauth-fa064.firebasestorage.app',
    iosBundleId: 'com.example.mytravel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBa7kGicUmPfm3cye1UZSKb9nkf21imSIs',
    appId: '1:899422984435:web:d6f63763affe689b80ff86',
    messagingSenderId: '899422984435',
    projectId: 'flutterauth-fa064',
    authDomain: 'flutterauth-fa064.firebaseapp.com',
    storageBucket: 'flutterauth-fa064.firebasestorage.app',
  );
}
